/* GNOME_Database_Report.idl
 * Copyright (C) 2001, The Free Software Foundation
 *
 * Authors:
 *      Carlos Perell\xf3 Mar\xedn <carlos@gnome-db.org>
 *
 * GNOME Database Report Engine interfaces.
 */

#ifndef __GNOME_Database_Report_idl__
#define __GNOME_Database_Report_idl__

#include <GNOME_Database.idl>

module GNOME {
	module Database {
		module Report {

			/*
			 * Engine interface - the report engine
			 */
			interface Engine : Bonobo::Unknown {
				/* document management */
				string runDocument (in string xml,
						    in GNOME::Database::ParameterList params);
			};
		};
	};
};

#endif

