create user gdauser identified by gdauser;
grant CREATE SESSION, ALTER SESSION, CREATE DATABASE LINK, CREATE MATERIALIZED VIEW, CREATE PROCEDURE, CREATE PUBLIC SYNONYM, CREATE ROLE, CREATE SEQUENCE, CREATE SYNONYM, CREATE TABLE, CREATE TRIGGER, CREATE TYPE, CREATE VIEW, UNLIMITED TABLESPACE to gdauser;

ALTER USER hr ACCOUNT UNLOCK;
ALTER USER hr IDENTIFIED BY gdauser;

QUIT
