/* -*- Mode: IDL; tab-width: 8; indent-tabs-mode: t; c-basic-offset: 8 -*- */
#ifndef __command__
#define __command__ 1

#include <Bonobo.idl>
#include "GDA_Recordset.idl"
#include "GDA_Parameter.idl"

module GDA {
	const unsigned long CMD_NORECORDS=0x80000000;
	enum CommandType {
		COMMAND_TYPE_TEXT,
		COMMAND_TYPE_TABLE,
		COMMAND_TYPE_TABLEDIRECT,
		COMMAND_TYPE_STOREDPROCEDURE,
		COMMAND_TYPE_FILE,
		COMMAND_TYPE_XML
	};
	
	interface Command : Bonobo::Unknown {
		attribute string           text;
		attribute CommandType      type;
	
		Recordset open (in CmdParameterSeq param, in CursorType ct, in LockType lt, out unsigned long affected)
				  raises (DriverError);
	};
};

#endif
