/* -*- Mode: IDL; tab-width: 8; indent-tabs-mode: t; c-basic-offset: 8 -*- */
#ifndef __error__
#define __error__ 1

module GDA {
	struct Error {
		string description;
		long   number;
		string source;
		string sqlstate;
		string nativeMsg;
	};
	
	typedef sequence<Error> ErrorSeq;
	
	exception DriverError {
		ErrorSeq errors;
		string   realcommand;
	};
	exception NotSupported {
		string errormsg;
	};
};

#endif
