/* -*- Mode: IDL; tab-width: 8; indent-tabs-mode: t; c-basic-offset: 8 -*- */

#include "GDA_Error.idl"

#ifndef __recordset__
#define __recordset__ 1

#include <Bonobo.idl>

module GDA {

	enum LockType {
		LOCK_READONLY,
		LOCK_PESSIMISTIC,
		LOCK_OPTIMISTIC,
		LOCK_BATCH
	};
	enum CursorType {
		OPEN_FWDONLY,
		OPEN_KEYSET,
		OPEN_DYNAMIC,
		OPEN_STATIC
	};
	
	enum Option {
		ADD_NEW,
		APPROX_POS,
		BOOKMARK,
		DELETE,
		HOLD_RECS,
		MOVE_PREV,
		DO_RESYNC,
		DO_UPDATE,
		UPDATE_BATCH
	};
	
	interface Recordset : Bonobo::Unknown {

		typedef  sequence<Row> Chunk;

		long          getRowCount();
		long          close();
		long          moveFirst();
		long          moveLast();
		long          moveNext();
		long          movePrev();
		long          reQuery();
		boolean       supports(in Option what);
		Chunk         fetch(in long count) raises(NotSupported, DriverError);
		RowAttributes describe();
	};
};

#endif
