/* -*- Mode: IDL; tab-width: 8; indent-tabs-mode: t; c-basic-offset: 8 -*- */

#ifndef __GNOME_Database_Field_idl__
#define __GNOME_Database_Field_idl__ 1

module GNOME {
module Database {
	enum ValueType {
		TypeNull,    TypeBigint, TypeBinary,
		TypeBoolean, TypeBstr,   TypeChar,
		TypeCurrency,TypeDate,   TypeDbDate,
		TypeDbTime,  TypeDbTimestamp, TypeDecimal,
		TypeDouble,  TypeError,  TypeInteger,
		TypeLongvarbin, TypeLongvarchar, TypeLongvarwchar,
		TypeNumeric, TypeSingle, TypeSmallint,
		TypeTinyint, TypeUBigint, TypeUSmallint,
		TypeVarchar, TypeVarbin,  TypeVarwchar,
		TypeFixchar, TypeFixbin,  TypeFixwchar,
		TypeUnknown, TypeLastValue
	};

	typedef long Date;
	struct  DbDate{
		short year;
		unsigned short month;
		unsigned short day;
	};
	struct DbTime {
		unsigned short hour;
		unsigned short minute;
		unsigned short second;
	};
	struct DbTimestamp {
		short year;
		unsigned short month;
		unsigned short day;
		unsigned short hour;
		unsigned short minute;
		unsigned short second;
		unsigned long  fraction;
	};
	typedef sequence<octet> VarBinString; 
	
	typedef any Value;
	struct FieldAttributes {
		long       definedSize;
		string     name;
		long       scale;
		ValueType  gdaType;
		long       cType;
		long       nativeType;
	};
	struct Field {
		long actualSize;
		Value value;
		FieldAttributes attributes;
	};
	typedef sequence<Field>           Row;
	typedef sequence<FieldAttributes> RowAttributes;

};
};

#endif
