/* -*- Mode: IDL; tab-width: 8; indent-tabs-mode: t; c-basic-offset: 8 -*- */
#ifndef __GDA_Parameter_idl__
#define __GDA_Parameter_idl__ 1

module GDA {
	interface Parameter {
		typedef sequence<octet> VarBinString;

		long    appendChunk(in VarBinString data);
	};
	
	enum ParameterDirection {
		PARAM_IN,
		PARAM_OUT,
		PARAM_INOUT
	};
	struct CmdParameter {
		FieldValue         value;
		ParameterDirection dir;
		string             name;
		long               precision;
		long               scale;
	};
	typedef sequence<CmdParameter> CmdParameterSeq;
};
  
#endif
