/* -*- Mode: IDL; tab-width: 8; indent-tabs-mode: t; c-basic-offset: 8 -*- */
#ifndef __GNOME_Database_Error_idl__
#define __GNOME_Database_Error_idl__ 1

module GNOME {
module Database {
	struct Error {
		string description;
		long   number;
		string source;
		string sqlstate;
		string nativeMsg;
	};
	
	typedef sequence<Error> ErrorSeq;
	
	exception DriverError {
		ErrorSeq errors;
		string   realcommand;
	};
	exception NotSupported {
		string errormsg;
	};
};
};

#endif
