/* -*- Mode: IDL; tab-width: 8; indent-tabs-mode: t; c-basic-offset: 8 -*- */
#ifndef __GNOME_Database_idl__
#define __GNOME_Database_idl__ 1

#include <GNOME_Database_Error.idl>
#include <GNOME_Database_Listener.idl>
#include <GNOME_Database_Field.idl>
#include <GNOME_Database_Parameter.idl>
#include <GNOME_Database_Recordset.idl>
#include <GNOME_Database_Command.idl>
#include <GNOME_Database_Error.idl>
#include <GNOME_Database_Connection.idl>

#endif


