#include <Bonobo.idl>

#ifndef __GDA_Listener_idl__
#define __GDA_Listener_idl__

module GDA {
	/*
         * Listener interface, implemented by GDA clients to
         * receive notifications from providers
         */
        enum ListenerAction {
		LISTENER_ACTION_DATABASE,
		LISTENER_ACTION_ERROR,
		LISTENER_ACTION_SHUTDOWN
	};

	interface Listener : Bonobo::Unknown {
		void notifyAction (in string message,
				   in ListenerAction action,
				   in string description);
	};

};

#endif
