#ifndef __GNOME_Database_idl__
#define __GNOME_Database_idl__ 1

#include <Bonobo.idl>

module GNOME {
	module Database {
		/*
		 * Basic types
		 */
		typedef any Value;

		struct Parameter {
			string name;
			Value value;
		};
		typedef sequence<Parameter> ParameterList;

		/*
		 * GDA data types
		 */
		enum ValueType {
			TYPE_NULL,
			TYPE_BIGINT,
			TYPE_BINARY,
			TYPE_BOOLEAN,
			TYPE_BSTR,
			TYPE_CHAR,
			TYPE_CURRENCY,
			TYPE_DATE,
			TYPE_TIME,
			TYPE_TIMESTAMP,
			TYPE_DECIMAL,
			TYPE_DOUBLE,
			TYPE_INTEGER,
			TYPE_LONGVARBIN,
			TYPE_LONGVARCHAR,
			TYPE_LONGVARWCHAR,
			TYPE_NUMERIC,
			TYPE_SINGLE,
			TYPE_SMALLINT,
			TYPE_TINYINY,
			TYPE_VARCHAR,
			TYPE_VARBIN,
			TYPE_VARWCHAR,
			TYPE_FIXCHAR,
			TYPE_FIXBIN,
			TYPE_FIXWCHAR,
			TYPE_UNKNOWN
		};

		struct Date{
			short year;
			unsigned short month;
			unsigned short day;
		};
		struct Time {
			unsigned short hour;
			unsigned short minute;
			unsigned short second;
		};
		struct Timestamp {
			short year;
			unsigned short month;
			unsigned short day;
			unsigned short hour;
			unsigned short minute;
			unsigned short second;
			unsigned long  fraction;
		};

		/*
		 * Error management
		 */
		struct Error {
			string description;
			long   number;
			string source;
			string sqlstate;
		};

		typedef sequence<Error> ErrorSeq;

		exception DriverError {
			ErrorSeq errors;
			string   realcommand;
		};

		/*
		 * The Recordset interface contains all information
		 * about a set of rows returned by the underlying
		 * provider as a result of executing a command
		 */
		struct FieldAttributes {
			long       definedSize;
			string     name;
			long       scale;
			ValueType  gdaType;
		};
		struct Field {
			long actualSize;
			Value value;
			FieldAttributes attributes;
		};
		typedef sequence<FieldAttributes> RowAttributes;
		typedef sequence<Field> Row;

		interface Recordset : Bonobo::Unknown {
			RowAttributes describe ();

			boolean moveFirst ();
			boolean moveNext ();
			boolean movePrevious ();
			boolean moveLast ();

			Row fetch ();
		};
		typedef sequence<Recordset> RecordsetList;

		/*
		 * The Command struct contains information about a
		 * command to be executed on the server
		 */
		enum CommandType {
			COMMAND_TYPE_SQL,
			COMMAND_TYPE_XML,
			COMMAND_TYPE_PROCEDURE,
			COMMAND_TYPE_TABLE,
			COMMAND_TYPE_INVALID
		};

		struct Command {
			string text;
			CommandType type;
		};

		/*
		 * The Client interface is implemented by GDA clients,
		 * and is used by providers to communicate stuff to
		 * connected clients.
		 */
		enum ActionId {
			ACTION_CLIENT_CONNECTED,
			ACTION_CLIENT_EXITED,
			ACTION_TRANSACTION_STARTED,
			ACTION_TRANSACTION_FINISHED,
			ACTION_TRANSACTION_ABORTED,
		};

		interface Client : Bonobo::Unknown {
			void notifyAction (in ActionId action, in ParameterList params);
		};

		/*
		 * The Connection interface provides access to an
		 * open database connection.
		 */
		typedef string TransactionId;

		interface Connection : Bonobo::Unknown {
			/* opening/closing connections */
			boolean open (in Client client,
				      in string cnc_string,
				      in string username,
				      in string password) raise DriverError;
			boolean close (in Client client) raise DriverError;

			/* command execution */
			RecordsetList executeCommand (in Command cmd,
						      in ParameterList params)
				raise DriverError;

			/* transactions */
			boolean beginTransaction (TransactionId id) raise DriverError;
			boolean commitTransaction (TransactionId id) raise DriverError;
			boolean rollbackTransaction (TransactionId id) raise DriverError;
		};

		/*
		 * The Provider interface is the CORBA interface to be
		 * implemented by the different providers
		 */
		interface Provider : Bonobo::Unknown {
			/* information methods */
			string getVersion ();

			/* basic operations */
			Connection createConnection ();
		};
	};

};

#endif


