.\" 
.\" gda-config-tool man page
.\" (C) 2002 GNOME Foundation
.\" Author:
.\"   Gonzalo Paniagua Javier (gonzalo@gnome-db.org)
.\"
.TH gda-config-tool "1" "October 2002" "gda-config-tool (libgda)" "User Commands"
.SH NAME
gda-config-tool \- Tool for managing libgda configuration file.
.SH SYNOPSIS
.PP
.B gda-config-tool [OPTIONS]
.SH DESCRIPTION
The \fIgda-config-tool\fP program can be used create/edit/remove a libgda
provider. It can be used both as a command line program and an interactive
program.
.SH OPTIONS
.PP
The following options are supported:
.TP
\fB\-?\fR, \fB\-\-help\fR
Displays command line options.
.TP
\fB--usage\fR
Display brief usage message.
.TP
\fB--l\fR, \fB\-\-list\-providers\fR
Lists installed providers.
.TP
\fB--L\fR, \fB\-\-list\-datasources\fR
Lists configured data sources.
.TP
\fB--n\fR, \fB\-\-name=NAME\fR
User-assigned name for the provider and connection settings.
.TP
\fB--u\fR, \fB\-\-user=NAME\fR
User name to pass to the provider when connecting.
.TP
\fB--p\fR, \fB\-\-password=NAME\fR
Password for the given user to pass to the DB backend.
.TP
\fB--P\fR, \fB\-\-provider=NAME\fR
Provider name.
.TP
\fB--d\fR, \fB\-\-DSN="NAME=VALUE;..."\fR
Semi-colon separated list of parameter=value option to pass to the provider.
.SH ENVIRONMENT VARIABLES
.TP
NONE
.SH FILES
.PP
$(sysconfdir)/libgda/config
.IP
Global configurations settings read for every user.
.PP
${HOME}/.libgda/config
.IP
User settings. Override global settings.
.SH SEE ALSO
.BR mergeant(1),
.BR gda-config(5)


